# Site settings
title: Madhav Mehndiratta
description: Madhav Mehndiratta
# baseurl: "/particle" # the subpath of your site, e.g. /blog
# url: "localhost:3000" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Madhav Mehndiratta
user_description: I am a 12th grade student at Sacred Heart Convent School, Jagadhri. I am extremely interested in Cyber Security and wannabe a Red Teamer. I enjoy hacking stuff as much as I enjoy writing about it. You can check my blog where you will find write-ups for CTF challenges, articles about certain topics and even quick notes about different things that I want to remember.
user_title: Infosec Enthusiast
email: madhavmehndiratta@gmail.com.com
twitter_username: 0xm1m3
github_username:  madhavmehndiratta
# gplus_username:  madhavmehndiratta

# Google-analytics
google-analytics:
  id: ""

exclude: ['package.json', 'src' , 'node_modules']
